### ISSUE TITLE
Gợi ý

### ISSUE THREAD

**Issue by katyperrycbt** [KhangNguyenIU/Chat-Web-MERN-stack---Web-application-development-project#1]
Nên tách ra 2 repos để dễ quản lý và deploy nha, với tên repo hơi rối kk

**Comment by KhangNguyenIU** [comment]
Kk đúng là sai lầm nè. Deploy trên railway nó k cho cd vào folder backend

Vào 13:51, T.5, 14 Th4, 2022 Tran Trong Thuc ***@***.***> đã
viết:
